### ISSUE TITLE
Dividere in 2 pagine votazione e risultati

### ISSUE THREAD

**Issue by pesto13** [fmanto01/party_game#91]
![image](https://github.com/user-attachments/assets/589d7d14-497c-4c93-8734-4709825ca1c0)

questo deve avvenire come voleva zelo.

chi vota diventa grigio / spunta per poi andare nella seconda pagina

![image](https://github.com/user-attachments/assets/2600961e-7550-43e0-ba6b-924796e8e947)

**Comment by fmanto01** [comment]
Migliorabile ma comunque fatto un discreto lavoro
